Project/Project/Controllers/GirisController.cs
using Project.Identity;
using Project.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project.Controllers
{
    public class GirisController : Controller
    {
        private SignInManager<Kullanici> girisYoneticisi;
        private UserManager<Kullanici> kullaniciYoneticisi;

        public GirisController(UserManager<Kullanici> _kullaniciYoneticisi, SignInManager<Kullanici> _girisYoneticisi)
        {
            girisYoneticisi = _girisYoneticisi;
            kullaniciYoneticisi = _kullaniciYoneticisi;
        }
        public IActionResult Index(string _url = null)
        {
            return View(new Giris()
            {
                Url = _url
            });
        }

        [HttpPost]
        public async Task<IActionResult> Index(Giris model)
        {
            if (ModelState.IsValid)
            {
                var user = await kullaniciYoneticisi.FindByEmailAsync(model.Email);
                if (user == null)
                {
                    ModelState.AddModelError("", "Bu E-Mail Adresine Ait Bir Hesap Bulunamadı.");
                }
                else
                {
                    var result = await girisYoneticisi.PasswordSignInAsync(user, model.Sifre, false, false);
                    if (result.Succeeded)
                    {
                        model.KullaniciID = user.Id;
                        model.Email = user.Email;
                        model.Sifre = user.PasswordHash;
                        model.KullaniciAdi = user.UserName;
                        return Redirect(model.Url ?? "~/");
                    }
                    ModelState.AddModelError("", "E-Mail Adresi ya da Şifre Yanlış");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Cikis()
        {
            await girisYoneticisi.SignOutAsync();
            return Redirect("~/");
        }
    }
}

Project/Project/Controllers/KayitController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Project.Identity;
using Project.Models;
using Microsoft.AspNetCore.Identity;

namespace DKGamers.Controllers
{
    public class KayitController : Controller
    {
        private UserManager<Kullanici> kullaniciYoneticisi;

        public KayitController(UserManager<Kullanici> _kullaniciYoneticisi)
        {
            kullaniciYoneticisi = _kullaniciYoneticisi;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(Kayit model)
        {
            if (ModelState.IsValid)
            {
                Kullanici kullanici = new Kullanici();
                kullanici.UserName = model.KullaniciAdi;
                kullanici.Email = model.Email;

                var result = await kullaniciYoneticisi.CreateAsync(kullanici, model.Sifre);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }
            return View(model);
        }
    }
}

Project/Project/Controllers/YeniController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Project.Models;
using Microsoft.EntityFrameworkCore;
using Project.Data;
using Microsoft.AspNetCore.Identity;
using Project.Identity;

namespace Project.Controllers
{
    public class YeniController : Controller
    {
        private Context context;

        private UserManager<Kullanici> kullaniciYoneticisi;
        public YeniController(UserManager<Kullanici> _kullaniciYoneticisi, Context context)
        {
            kullaniciYoneticisi = _kullaniciYoneticisi;
            this.context = context;
        }
        public IActionResult Index()
        {
            var filmler = context.Film.Where(t => t.filmGosterilsinmi == false).ToList();
            filmler = filmler.OrderByDescending(x => x.PiyasayaSurulmeTarihi).ToList();
            filmler = filmler.Take(10).ToList();

            return View(new FilmListViewModel()
            {
                Filmler = filmler

            });
        }
        public IActionResult Detail(int id)
        {
            Film film = context.Film.Include(i => i.FilmKategorileri).ThenInclude(i => i.Kategori).FirstOrDefault(i => i.FilmID == id);
            var yorumlar = context.Yorum.Include(i => i.Film).Where(i => i.FilmID == id).ToList();
            var favorilerdemi = context.Favori.Any(i => i.Film.FilmID == id && i.KullaniciAdi == User.Identity.Name);
            film.GoruntulenmeSayisi++;
            context.Film.Update(film);
            context.SaveChanges();
            return View(new FilmDetailViewModel()
            {
                Film = film,
                Yorumlar = yorumlar,
                favorilerdemi = favorilerdemi
            });
        }

        [HttpPost]
        public IActionResult CreateComment(YorumModel model)
        {
            var user = kullaniciYoneticisi.FindByNameAsync(User.Identity.Name).Result;
            var Yorum = new Yorum()
            {
                OlusturulmaTarihi = DateTime.Now,
                KullaniciAdi = user.UserName,
                FilmID = model.FilmID,
                YapilanYorum = model.YapilanYorum
            };
            context.Yorum.Add(Yorum);
            context.SaveChanges();
            return Redirect("/Yeni/Detail/" + model.FilmID);
        }
    }
}

Project/Project/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
          integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.5/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/css/site.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand " href="/admin">Admin Panel</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="mr-2 fas fa-user fa-fw"></i>@User.Identity.Name</a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="/admin">Admin Paneli</a>
                    <a class="dropdown-item" href="/">Siteye geri dön</a>

                </div>
            </li>
        </ul>
    </nav>

    <div class="container-fluid my-2">
        <div class="row">


            <div class="col-md-2">
                <div class="list-group list-group-flush sticky-top shadow">
                    <a href="/admin" class="list-group-item list-group-item-action bg-dark text-white">
                        Anasayfa
                    </a>
                    <a href="/admin/kullanici/list" class="list-group-item list-group-item-action"><i class=""></i>Kullanıcılar</a>
                    <a href="/admin/haber/" class="list-group-item list-group-item-action"><i class=""></i>Haberler</a>
                    <a href="/admin/haberekle/list" class="list-group-item list-group-item-action"><i class=""></i>Haber Ekle</a>
                    <a href="/admin/film/" class="list-group-item list-group-item-action"><i class=""></i>Filmler</a>
                    <a href="/admin/filmekle/" class="list-group-item list-group-item-action"><i class=""></i>Film Ekle</a>
                </div>
            </div>
            <div class="col-md-10">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.5/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#example').DataTable({
                language: {
                    url: "https://cdn.datatables.net/plug-ins/1.10.20/i18n/Turkish.json",
                },
            });
        });
    </script>
    @RenderSection("Scripts", false)
</body>
</html>

Project/Project/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> LocOptions

@{
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureList = LocOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = x.Name }).ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path}{Context.Request.QueryString}";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Film Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: #f9f4fa">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white text-white border-bottom box-shadow mb-3 ">
            <div class="container">
                <a class="navbar-brand text-black-50" asp-area="" asp-controller="Home" asp-action="Index">
                    <span class="icon icon-home"></span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="Home" asp-action="Index">@localizer["Anasayfa"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="Yeni" asp-action="Index">@localizer["Yeni"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="Populer" asp-action="Index">@localizer["Popüler"]</a>
                        </li>
                        <li class="nav-item item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="Filmler" asp-action="Index">@localizer["Filmler"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="Hakkinda" asp-action="Index">@localizer["Hakkımızda"]</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-black-50" asp-area="" asp-controller="Admin" asp-action="Index">@localizer["Admin Paneli"]</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="ml-2">
                        <form style="margin-top:1%; margin-right:5px" asp-action="CultureManagement" asp-controller="Home" method="post" asp-route-returnUrl="@returnUrl">
                            <select name="Culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList" class="form-control" onchange="this.form.submit();"></select>
                        </form>
                    </div>
                    <form class="form-inline">
                        <a asp-area="" asp-controller="Yorum" asp-action="Index">
                            <span class="icon icon-comment" style=" margin-right: 10px"></span>
                        </a>
                        <a asp-area="" asp-controller="Favori" asp-action="Index">
                            <span class="icon icon-like" style=" margin-right: 10px"></span>
                        </a>
                        <a asp-area="" asp-controller="Profil" asp-action="Index">
                            <span class="icon icon-profile" style=" margin-right: 10px"></span>
                        </a>
                        <button class="btn  text-black-50 mb-2" style="margin-top:1%;" type="submit" asp-area="" asp-controller="Giris" asp-action="Cikis">@localizer["Çıkış Yap"]</button>
                    </form>
                }
                else
                {
                    <div class="ml-2">
                        <form style="margin-top:1%; margin-right:5px" asp-action="CultureManagement" asp-controller="Home" method="post" asp-route-returnUrl="@returnUrl">
                            <select name="Culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList" class="form-control" onchange="this.form.submit();"></select>
                        </form>
                    </div>
                    <form class="form-inline">
                        <button class="btn btn-primary text-black mb-2" style="margin-top:1%; margin-right:5px" type="submit";  asp-area="" asp-controller="Giris" asp-action="Index">@localizer["Giriş Yap"]</button>
                        <button class="btn btn-primary text-black mb-2" style="margin-top:1%" type="submit" asp-area="" asp-controller="Kayit" asp-action="Index">@localizer["Kayıt Ol"]</button>
                    </form>
                }
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container bg-white text-dark">
            &copy; 2021 - FilmProject 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Project/Project/Views/Shared/adminDetailLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
          integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.5/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/css/site.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/admin" >Admin Panel</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="mr-2 fas fa-user fa-fw"></i>@User.Identity.Name</a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="/admin">Admin Paneli</a>
                    <a class="dropdown-item" href="/">Siteye geri dön</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/account/logout">
                        <i class="fas fa-sign-out-alt mr-1"></i>
                        Çıkış Yap
                    </a>
                </div>
            </li>
        </ul>
    </nav>

    <div class="container-fluid my-2">
        <div class="row">

            <div class="col-md-10">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.5/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#example').DataTable({
                language: {
                    url: "https://cdn.datatables.net/plug-ins/1.10.20/i18n/Turkish.json",
                },
            });
        });
    </script>
    @RenderSection("Scripts", false)
</body>
</html>